//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubbing.Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadjaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogadjaj()
        {
            this.Recenzijas = new HashSet<Recenzija>();
            this.Slikas = new HashSet<Slika>();
            this.Stols = new HashSet<Stol>();
        }
    
        public int id_dogadjaj { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public System.DateTime datum_pocetka { get; set; }
        public System.DateTime datum_zavrsetka { get; set; }
        public int cijena_ulaznice { get; set; }
        public int max_rezervacija { get; set; }
        public int fk_klub { get; set; }
    
        public virtual Klub Klub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slika> Slikas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stol> Stols { get; set; }
    }
}
