//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubbing.Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavijest
    {
        public int id_obavijest { get; set; }
        public string opis { get; set; }
        public System.DateTime datum_obavijesti { get; set; }
        public int fk_klub { get; set; }
        public byte vrsta { get; set; }
    
        public virtual Klub Klub { get; set; }

    }
}
