//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubbing.Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int id_recenzija { get; set; }
        public int ocjena { get; set; }
        public string opis { get; set; }
        public Nullable<int> fk_dogadjaj { get; set; }
        public Nullable<int> fk_klub { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
        public virtual Klub Klub { get; set; }
    }
}
