//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubbing.Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int id_rezervacija { get; set; }
        public int broj_ljudi { get; set; }
        public System.DateTime datum_rezervacije { get; set; }
        public int fk_korisnik { get; set; }
        public int fk_stol { get; set; }
        public int fk_status { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual StatusRezervacije StatusRezervacije { get; set; }
        public virtual Stol Stol { get; set; }
    }
}
