//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubbing.Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slika
    {
        public int id_slika { get; set; }
        public byte[] slika1 { get; set; }
        public int fk_dogadjaj { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
